### ISSUE TITLE
remove mention of italics in the summary command 

### ISSUE THREAD

**Issue by WesleyBLDC** [AY2223S2-CS2103-W16-4/tp#165] opened 2023-04-05 08:46 UTC
![image](https://user-images.githubusercontent.com/28299779/230030014-f8ad3a2f-67fc-4ba6-ab22-57161b136b28.png)

**Comment by evanpy** [comment] 2023-04-06 20:21
Closing due to duplicate of issue [#137](https://github.com/AY2223S2-CS2103-W16-4/tp/issues/137)

**Closed by evanpy** 2023-04-06 20:21 UTC
Labels: documentation
